# Define the stages of the pipeline
stages:
  - test
  - build
  - deploy

# Use Docker as the default image
image: docker:latest

# Define services needed for Docker in Docker
services:
  - docker:dind

# Define global variables
variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: registry.gitlab.com/$CI_PROJECT_PATH/whales_identify

# Test Stage
test:
  stage: test
  script:
    - apk add --no-cache curl
    - curl -sSL https://install.python-poetry.org | python3 -
    - export PATH="$HOME/.local/bin:$PATH"
    - poetry install
    - poetry run pytest  # Assumes you have tests configured with pytest

# Build Stage
build:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_NAME:$CI_COMMIT_REF_NAME .
    - docker push $IMAGE_NAME:$CI_COMMIT_REF_NAME

# Deploy Stage
deploy:
  stage: deploy
  only:
    - main  # Only deploy from the main branch
  script:
    - docker pull $IMAGE_NAME:$CI_COMMIT_REF_NAME
    - docker tag $IMAGE_NAME:$CI_COMMIT_REF_NAME $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:latest
  environment:
    name: production
